### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by NGoedix** [McDaived/CS2-Patch-Access#1]
![image](https://github.com/McDaived/CS2-Patch-Access/assets/91873998/f4ac1fbb-091c-4653-840d-6f95b17396ce)

**Comment by NGoedix** [comment]
(I have steam running)

**Comment by McDaived** [comment]
![image](https://github.com/McDaived/CS2-Patch-Access/assets/18085492/a077f83b-222c-4747-8c6f-39d455fc9310)

it perfactly work , just make sure steam on the last version , if not work delete the game and download latest version cs2downloader .

**Comment by NGoedix** [comment]
I have the latest steam version (checked the update) and i tried to remove the game and tried to install again with the CS2Downloader 1.3

**Comment by NGoedix** [comment]
I need in the library the CS?

**Comment by NGoedix** [comment]
Oh, yep, that was the problem

**Comment by McDaived** [comment]
when u download the game from cs2downloader make sure press Y to patch it when download it done .

**Comment by McDaived** [comment]
> I need in the library the CS?

yes
