### ISSUE TITLE
Is this a problem?

### ISSUE THREAD

**Issue by bobba84** [McDaived/CS2-Patch-Access#3]
Press 'Y' for 'Yes' or 'N' for 'No' on your keyboard
y
patch out of date: game/csgo/bin/win64/server.dll | 7
failed to patch movement clamp
Finished Patches!

**Comment by McDaived** [comment]
is no longer available, because the final version of the game has been released.
**out of date now** it is designed to play the game on beta version, sry there is no longer a need to update it.
**thank you all.**
